#index:
#    path: /
#    controller: App\Controller\DefaultController::index

 


deletecommentaction:
    path: /comments/delete/{id}
    controller: App\Controller\AdminController::deletecomment







   